#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  1 09:59:34 2020

@author: joe
"""

from numba import jit, njit
import numpy as np


#%%
@jit
def compute_allocation0(q, X, lam):

    row = X.shape[0]
    
    result = [0] * row
    
    for i in range(0, row):
        result[i] = result[i] + sum(-X[i] * lam)
    
    qxl = q * result
    # qxl = q * np.exp(result)
    return qxl / sum(qxl)
#%%


%timeit compute_allocation(q, X, lamf)    

compute_allocation0(q, X, lamf)
